### ISSUE TITLE
ReadMe files

### ISSUE THREAD

**Issue by okonor** [handsomecode/astrology-motion-ios#1]
![implemented-animation](https://user-images.githubusercontent.com/2081318/27797545-e60188e4-602f-11e7-893f-51175333baaf.gif)
![demo](https://user-images.githubusercontent.com/2081318/28152290-742aa086-67c1-11e7-8e58-1cbf75dceaa3.gif)

**Comment by alexzub** [comment]
@okonor ReadMe file contains a copy-paste from another repo: "InteractiveSideMenu is available under the Apache License, Version 2.0. See the LICENSE file for more info."

**Comment by okonor** [comment]
Thanks Alex,
Fixed.

**Comment by okonor** [comment]
![330-60frames](https://user-images.githubusercontent.com/2081318/29116685-70f27a12-7d1d-11e7-9cda-0dcc4662ddb9.gif)
![astrology-demo](https://user-images.githubusercontent.com/2081318/29279886-190b0f9a-813b-11e7-8c42-5e856c384eec.gif)
